# Project keys
sonar.python.coverage.reportPaths=coverage.xml
sonar.organization=defk0rn
sonar.projectKey=DefK0rn_python-project-50

# Environment 
sonar.sources=gendiff
sonar.tests=tests
sonar.coverage.exclusions=tests/**,gendiff/scripts/**