sonar.python.coverage.reportPaths=coverage.xml # Путь к сгенерированному файлу покрытия (относительно корня проекта)
sonar.organization=defk0rn # Точный ключ организации в SonarQube
sonar.projectKey=DefK0rn_python-project-50 # Точный ключ проекта в SonarQube