name: gendiff CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
        # make depends on uv
      - name: Install dependencies
        run: |
          pip install uv
          make install
      - name: Run linter and pytest
        run: |
          make check
      - name: Run test coverage
        run: |
          make test-coverage
      #- name: Install tox and any other packages
      #  run: |
      #    pip install tox
      #- name: Run tox
      #  run: tox -e py
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}